---
title: "Clase1"
author: "Ilan Jinich"
output: html_document
---
##Introducción
#Solo es un draft, falta arreglar y agregar unas cosas



Vector
```{r}
x<-c(1,2,3,4)
x

y<-1:4
class(y)

d<-c(TRUE,FALSE)
class(d)

g<-c(10L,15L)
class(g)
g2<-as.numeric(g)
class(g2)

```

Lista

```{r}
y<-list ('a',125L,pi,TRUE)
y
str(y) #comentarios
```
Matriz

```{r}
m<-1:15
m

dim(m)<-c(3,5)
m

m<-matrix(1:15,nrow=3,ncol=5,byrow = TRUE)
m

v1<-1:3
v2<-4:6
a<-cbind(v1,v2)
b<-rbind(v1,v2)
a
b
```
Arreglo
```{r}
x<-array(1:20,dim=c(2,5,2))
x
```

Data Frame
```{r}
x<-data.frame(f=1:4,b=c(TRUE,FALSE,F,T))
x
nrow(x)
ncol(x)
x$b
names(x)<-c('a','b')
x
```
Consulta:
1)Vectores
```{r}
x<-1:10
x[2]
x[3:6]
x[-c(2,7)]
x[!x %in% c(7,14)]
y<-c('r','a')
y[1]
length(y)
x[x>6]
x[x>6 & x<=9]

```
Consulta, Matrices:

```{r}
matriz<-matrix(1:15,nrow=3,ncol=5)
dim(matriz)
matriz[2,3:5]
matriz
colnames(matriz)<-c('col',2,3,4,5)
colnames(matriz)
matriz[,2]

```
Consulta Data Frame
```{r}
class(cars)
dim(cars)
names(cars)
head(cars)
tail(cars)
head(cars$speed,2)

```
Variables de Control
if
```{r}
A<-T
B<-F
if(A){print('hola')}
if(B){print('B')}else{'A'}

```
for
```{r}
x<-20:40
seq_along(x)
for(i in seq_along(x)){print(x[i])}
for(i in x){print(i)}
```
while
```{r}
n<-1
while(n<=5){
  print(n)
  n<-n+1
}
```
repeat
```{r}
n<-1
repeat{
  if(n>10){break}
  print(n)
  n<-n+1
  }
