---
title: "Clase 4"
author: "Ilan Jinich"
date: "8 de febrero de 2018"
output: html_document
---
Las notas estan basadas en las de Andreu Boada de Atela (Enero 26, 2016).
```{r,eval=FALSE}
install.packages('ggplot2')
```


```{r}
library(ggplot2)
```

##A

```{r}
#Base de datos que vamos a usar
head(mpg) 
str(mpg)
```

##1

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point()
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class)) + 
  geom_point()
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy, size = drv,color=class)) + 
  geom_point()
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class, shape=fl,size=drv)) + 
  geom_point()
```
##2
```{r}
p <- ggplot(mpg, aes(x = displ, y = hwy))
p + geom_line()
```





##3
```{r}
p <- ggplot(mpg, aes(x = cty, y = hwy))
p + geom_point()
```


```{r}
p + geom_jitter() 
```

##4
```{r}
ggplot(mpg, aes(x = reorder(class, hwy), y = hwy)) + 
    geom_point()
```

```{r}
ggplot(mpg, aes(x = reorder(class, hwy), y = hwy)) + 
    geom_jitter() 
```

```{r}
ggplot(mpg, aes(x = reorder(class, hwy), y = hwy)) + 
    geom_boxplot() 
```

```{r}
ggplot(mpg, aes(x = reorder(class, hwy), y = hwy)) + 
    geom_jitter() +
    geom_boxplot()
```

```{r}
ggplot(mpg, aes(x = reorder(class, hwy,median), y = hwy)) + 
    geom_jitter() +
    geom_boxplot()
```

##B
http://r-statistics.co/Complete-Ggplot2-Tutorial-Part1-With-R-Code.html

```{r,cache=TRUE}
midwest <- read.csv("http://goo.gl/G1K41K")
class(midwest)
library(dplyr)
glimpse(midwest)
```
##1
```{r}
ggplot(midwest, aes(x=area, y=poptotal)) + geom_point()

```

```{r}
g <- ggplot(midwest, aes(x=area, y=poptotal)) + geom_point() + geom_smooth(method="lm",se=FALSE)
plot(g)
```
```{r}
g + xlim(0, 0.1) + ylim(0, 1000000)
```

```{r}
g <- ggplot(midwest, aes(x=area, y=poptotal)) + geom_point() + geom_smooth(method="lm")
g1 <- g + coord_cartesian(xlim=c(0,0.1), ylim=c(0, 1000000))
g1<-g1 + labs(title="Area Vs Population", subtitle="From midwest dataset", y="Population", x="Area", caption="Midwest Demographics")

print(g1)
                      
                          
```

```{r}
g <- ggplot(midwest, aes(x=area, y=poptotal,col=as.factor(inmetro))) + geom_point() + scale_colour_brewer(palette = "Set1")
print(g)
```

##C
##1
```{r}
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_jitter() +
  facet_wrap(~ cyl)
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_jitter() +
  facet_grid(.~ class)
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_jitter() +
  facet_grid(drv ~ class)
```

##2
```{r}
data(airquality)
ggplot(airquality, aes(x = Solar.R, y = Ozone)) + 
  geom_point() 
```

```{r}
#install.packages('Hmisc')
library(Hmisc) #Vamos a ver despues que es esto
airquality$Wind.cat <- cut2(airquality$Wind, g = 3) 

ggplot(airquality, aes(x = Solar.R, y = Ozone)) + 
  geom_point() +
  facet_wrap(~ Wind.cat)
```

```{r}
ggplot(airquality, aes(x = Solar.R, y = Ozone)) + 
  geom_point() +
  facet_wrap(~ Wind.cat) + 
  geom_smooth(span = 3)
```

##3
Pronto veremos Readr, ahorita solo lo vamos a usar para leer un csv. Los datos estan en el github.
```{r}
#install.packages('readr')
library('readr')
bnames <- read_csv('bnames.csv')
head(bnames)
library('dplyr')
```
```{r}
bnames_John <- 
  filter(bnames, name == "John")
ggplot(bnames_John, aes(x = year, y = percent)) +
  geom_point()
```

```{r}
ggplot(bnames_John, aes(x = year, y = percent, color = sex)) +
  geom_line()
```

##Ejercicio en clase
Juegen con msleep y hagan varias gráficas, traten de ver que encuentran.
```{r}
head(msleep)
```

